// ✅ AUTO-GENERATED. DO NOT EDIT BY HAND.
// ใช้: import { ADD_IMAGES } from "./imageManifest";
export const ADD_IMAGES = {
  "Activities/กิน": require("./Activities/กิน.png"),
  "Activities/ขับรถ": require("./Activities/ขับรถ.png"),
  "Activities/ดูหนัง": require("./Activities/ดูหนัง.png"),
  "Activities/ถ่ายรูป": require("./Activities/ถ่ายรูป.png"),
  "Activities/ทำงาน": require("./Activities/ทำงาน.png"),
  "Activities/ทำอาหาร": require("./Activities/ทำอาหาร.png"),
  "Activities/นอน": require("./Activities/นอน.png"),
  "Activities/พูด": require("./Activities/พูด.png"),
  "Activities/ฟัง": require("./Activities/ฟัง.png"),
  "Activities/วิ่ง": require("./Activities/วิ่ง.png"),
  "Activities/ว่ายน้ำ": require("./Activities/ว่ายน้ำ.png"),
  "Activities/ออกกำลังกาย": require("./Activities/ออกกำลังกาย.png"),
  "Activities/อ่าน": require("./Activities/อ่าน.png"),
  "Activities/เขียน": require("./Activities/เขียน.png"),
  "Activities/เดิน": require("./Activities/เดิน.png"),
  "Activities/เดินทาง": require("./Activities/เดินทาง.png"),
  "Activities/เต้น": require("./Activities/เต้น.png"),
  "Activities/เรียน": require("./Activities/เรียน.png"),
  "Activities/เล่น": require("./Activities/เล่น.png"),
  "Activities/เล่นเกม": require("./Activities/เล่นเกม.png"),
  "Animals/กบ": require("./Animals/กบ.png"),
  "Animals/กระต่าย": require("./Animals/กระต่าย.png"),
  "Animals/ควาย": require("./Animals/ควาย.png"),
  "Animals/งู": require("./Animals/งู.png"),
  "Animals/จระเข้": require("./Animals/จระเข้.png"),
  "Animals/ช้าง": require("./Animals/ช้าง.png"),
  "Animals/นก": require("./Animals/นก.png"),
  "Animals/ปลา": require("./Animals/ปลา.png"),
  "Animals/ปลาหมึก": require("./Animals/ปลาหมึก.png"),
  "Animals/ปู": require("./Animals/ปู.png"),
  "Animals/ผีเสื้อ": require("./Animals/ผีเสื้อ.png"),
  "Animals/มด": require("./Animals/มด.png"),
  "Animals/ม้า": require("./Animals/ม้า.png"),
  "Animals/ยีราฟ": require("./Animals/ยีราฟ.png"),
  "Animals/ยุง": require("./Animals/ยุง.png"),
  "Animals/ลิง": require("./Animals/ลิง.png"),
  "Animals/วัว": require("./Animals/วัว.png"),
  "Animals/สิงโต": require("./Animals/สิงโต.png"),
  "Animals/หมา": require("./Animals/หมา.png"),
  "Animals/หมี": require("./Animals/หมี.png"),
  "Animals/หมู": require("./Animals/หมู.png"),
  "Animals/เต่า": require("./Animals/เต่า.png"),
  "Animals/เสือ": require("./Animals/เสือ.png"),
  "Animals/แมลงวัน": require("./Animals/แมลงวัน.png"),
  "Animals/แมว": require("./Animals/แมว.png"),
  "Animals/ไก่": require("./Animals/ไก่.png"),
  "Colors/ขาว": require("./Colors/ขาว.jpg"),
  "Colors/ชมพู": require("./Colors/ชมพู.jpg"),
  "Colors/ดำ": require("./Colors/ดำ.jpg"),
  "Colors/ทอง": require("./Colors/ทอง.jpg"),
  "Colors/น้ำตาล": require("./Colors/น้ำตาล.jpg"),
  "Colors/น้ำเงิน": require("./Colors/น้ำเงิน.jpg"),
  "Colors/ฟ้า": require("./Colors/ฟ้า.jpg"),
  "Colors/ม่วง": require("./Colors/ม่วง.jpg"),
  "Colors/ส้ม": require("./Colors/ส้ม.jpg"),
  "Colors/เขียว": require("./Colors/เขียว.jpg"),
  "Colors/เงิน": require("./Colors/เงิน.jpg"),
  "Colors/เทา": require("./Colors/เทา.jpg"),
  "Colors/เหลือง": require("./Colors/เหลือง.jpg"),
  "Colors/แดง": require("./Colors/แดง.jpg"),
  "Emotions/กลัว": require("./Emotions/กลัว.png"),
  "Emotions/กังวล": require("./Emotions/กังวล.png"),
  "Emotions/ง่วง": require("./Emotions/ง่วง.png"),
  "Emotions/ดีใจ": require("./Emotions/ดีใจ.png"),
  "Emotions/ตกใจ": require("./Emotions/ตกใจ.png"),
  "Emotions/ผ่อนคลาย": require("./Emotions/ผ่อนคลาย.png"),
  "Emotions/ภูมิใจ": require("./Emotions/ภูมิใจ.png"),
  "Emotions/มีความสุข": require("./Emotions/มีความสุข.png"),
  "Emotions/รัก": require("./Emotions/รัก.png"),
  "Emotions/สงสัย": require("./Emotions/สงสัย.png"),
  "Emotions/สนุก": require("./Emotions/สนุก.png"),
  "Emotions/หิว": require("./Emotions/หิว.png"),
  "Emotions/เกลียด": require("./Emotions/เกลียด.png"),
  "Emotions/เครียด": require("./Emotions/เครียด.png"),
  "Emotions/เบื่อ": require("./Emotions/เบื่อ.png"),
  "Emotions/เสียใจ": require("./Emotions/เสียใจ.png"),
  "Emotions/เหงา": require("./Emotions/เหงา.png"),
  "Emotions/โกรธ": require("./Emotions/โกรธ.png"),
  "Food/กล้วย": require("./Food/กล้วย.png"),
  "Food/ขนมจีน": require("./Food/ขนมจีน.png"),
  "Food/ขนมปัง": require("./Food/ขนมปัง.png"),
  "Food/ข้าว": require("./Food/ข้าว.png"),
  "Food/ข้าวต้ม": require("./Food/ข้าวต้ม.png"),
  "Food/ข้าวผัด": require("./Food/ข้าวผัด.png"),
  "Food/ข้าวเหนียว": require("./Food/ข้าวเหนียว.png"),
  "Food/ชาเย็น": require("./Food/ชาเย็น.png"),
  "Food/ต้มยำ": require("./Food/ต้มยำ.png"),
  "Food/ทุเรียน": require("./Food/ทุเรียน.png"),
  "Food/น้ำตาล": require("./Food/น้ำตาล.png"),
  "Food/น้ำปลา": require("./Food/น้ำปลา.png"),
  "Food/ผัดไทย": require("./Food/ผัดไทย.png"),
  "Food/มะม่วง": require("./Food/มะม่วง.png"),
  "Food/ส้ม": require("./Food/ส้ม.png"),
  "Food/ส้มตำ": require("./Food/ส้มตำ.png"),
  "Food/เกลือ": require("./Food/เกลือ.png"),
  "Food/แกงเขียวหวาน": require("./Food/แกงเขียวหวาน.png"),
  "Food/แตงโม": require("./Food/แตงโม.png"),
  "Food/ไข่": require("./Food/ไข่.png"),
  "Food/ไอศกรีม": require("./Food/ไอศกรีม.png"),
  "Greetings & Common Phrases/ขอบคุณ": require("./Greetings & Common Phrases/ขอบคุณ.png"),
  "Greetings & Common Phrases/ขออนุญาต": require("./Greetings & Common Phrases/ขออนุญาต.png"),
  "Greetings & Common Phrases/ขอโทษ": require("./Greetings & Common Phrases/ขอโทษ.png"),
  "Greetings & Common Phrases/ขอให้มีความสุข": require("./Greetings & Common Phrases/ขอให้มีความสุข.png"),
  "Greetings & Common Phrases/ขอให้โชคดี": require("./Greetings & Common Phrases/ขอให้โชคดี.png"),
  "Greetings & Common Phrases/ชื่ออะไร": require("./Greetings & Common Phrases/ชื่ออะไร.png"),
  "Greetings & Common Phrases/ดีมาก": require("./Greetings & Common Phrases/ดีมาก.png"),
  "Greetings & Common Phrases/ฝันดี": require("./Greetings & Common Phrases/ฝันดี.png"),
  "Greetings & Common Phrases/ยินดีต้อนรับ": require("./Greetings & Common Phrases/ยินดีต้อนรับ.png"),
  "Greetings & Common Phrases/ยินดีที่ได้รู้จัก": require("./Greetings & Common Phrases/ยินดีที่ได้รู้จัก.png"),
  "Greetings & Common Phrases/ลาก่อน": require("./Greetings & Common Phrases/ลาก่อน.png"),
  "Greetings & Common Phrases/สบายดีไหม": require("./Greetings & Common Phrases/สบายดีไหม.png"),
  "Greetings & Common Phrases/สวัสดี": require("./Greetings & Common Phrases/สวัสดี.png"),
  "Greetings & Common Phrases/เจอกันใหม่": require("./Greetings & Common Phrases/เจอกันใหม่.png"),
  "Greetings & Common Phrases/เท่าไหร่": require("./Greetings & Common Phrases/เท่าไหร่.png"),
  "Greetings & Common Phrases/เยี่ยมเลย": require("./Greetings & Common Phrases/เยี่ยมเลย.png"),
  "Greetings & Common Phrases/ใช่": require("./Greetings & Common Phrases/ใช่.png"),
  "Greetings & Common Phrases/ไม่ใช่": require("./Greetings & Common Phrases/ไม่ใช่.png"),
  "Level Advanced/การจราจร": require("./Level Advanced/การจราจร.jpg"),
  "Level Advanced/การศึกษา": require("./Level Advanced/การศึกษา.jpg"),
  "Level Advanced/การเมือง": require("./Level Advanced/การเมือง.png"),
  "Level Advanced/ดนตรี": require("./Level Advanced/ดนตรี.png"),
  "Level Advanced/ดาราศาสตร์": require("./Level Advanced/ดาราศาสตร์.jpg"),
  "Level Advanced/นวัตกรรม": require("./Level Advanced/นวัตกรรม.png"),
  "Level Advanced/ประชาธิปไตย": require("./Level Advanced/ประชาธิปไตย.jpg"),
  "Level Advanced/ประวัติศาสตร์": require("./Level Advanced/ประวัติศาสตร์.png"),
  "Level Advanced/ปัญญาประดิษฐ์": require("./Level Advanced/ปัญญาประดิษฐ์.png"),
  "Level Advanced/พลังงาน": require("./Level Advanced/พลังงาน.png"),
  "Level Advanced/ภูมิศาสตร์": require("./Level Advanced/ภูมิศาสตร์.png"),
  "Level Advanced/วัฒนธรรม": require("./Level Advanced/วัฒนธรรม.jpg"),
  "Level Advanced/วิทยาศาสตร์": require("./Level Advanced/วิทยาศาสตร์.jpg"),
  "Level Advanced/ศิลปะ": require("./Level Advanced/ศิลปะ.png"),
  "Level Advanced/สังคม": require("./Level Advanced/สังคม.png"),
  "Level Advanced/สิ่งแวดล้อม": require("./Level Advanced/สิ่งแวดล้อม.jpg"),
  "Level Advanced/สุขภาพ": require("./Level Advanced/สุขภาพ.jpg"),
  "Level Advanced/อุตสาหกรรม": require("./Level Advanced/อุตสาหกรรม.png"),
  "Level Advanced/เทคโนโลยี": require("./Level Advanced/เทคโนโลยี.png"),
  "Level Advanced/เศรษฐกิจ": require("./Level Advanced/เศรษฐกิจ.png"),
  "Objects/กระเป๋า": require("./Objects/กระเป๋า.png"),
  "Objects/กุญแจ": require("./Objects/กุญแจ.png"),
  "Objects/คอมพิวเตอร์": require("./Objects/คอมพิวเตอร์.png"),
  "Objects/ดินสอ": require("./Objects/ดินสอ.png"),
  "Objects/ตู้เย็น": require("./Objects/ตู้เย็น.png"),
  "Objects/ทีวี": require("./Objects/ทีวี.png"),
  "Objects/ประตู": require("./Objects/ประตู.png"),
  "Objects/ปากกา": require("./Objects/ปากกา.png"),
  "Objects/ผ้าห่ม": require("./Objects/ผ้าห่ม.png"),
  "Objects/พัดลม": require("./Objects/พัดลม.png"),
  "Objects/รองเท้า": require("./Objects/รองเท้า.png"),
  "Objects/สมุด": require("./Objects/สมุด.png"),
  "Objects/หนังสือ": require("./Objects/หนังสือ.png"),
  "Objects/หน้าต่าง": require("./Objects/หน้าต่าง.png"),
  "Objects/หมวก": require("./Objects/หมวก.png"),
  "Objects/หมอน": require("./Objects/หมอน.png"),
  "Objects/เก้าอี้": require("./Objects/เก้าอี้.png"),
  "Objects/เสื้อ": require("./Objects/เสื้อ.png"),
  "Objects/โต๊ะ": require("./Objects/โต๊ะ.png"),
  "Objects/โทรศัพท์": require("./Objects/โทรศัพท์.png"),
  "Occupations/ทนายความ": require("./Occupations/ทนายความ.png"),
  "Occupations/นักการตลาด": require("./Occupations/นักการตลาด.png"),
  "Occupations/นักจิตวิทยา": require("./Occupations/นักจิตวิทยา.png"),
  "Occupations/นักพัฒนาเว็บ": require("./Occupations/นักพัฒนาเว็บ.png"),
  "Occupations/นักพัฒนาแอป": require("./Occupations/นักพัฒนาแอป.png"),
  "Occupations/นักวิจัย": require("./Occupations/นักวิจัย.png"),
  "Occupations/นักวิทยาศาสตร์": require("./Occupations/นักวิทยาศาสตร์.png"),
  "Occupations/นักวิเคราะห์ข้อมูล": require("./Occupations/นักวิเคราะห์ข้อมูล.png"),
  "Occupations/นักแปล": require("./Occupations/นักแปล.png"),
  "Occupations/ยูทูบเบอร์": require("./Occupations/ยูทูบเบอร์.png"),
  "Occupations/ล่าม": require("./Occupations/ล่าม.png"),
  "Occupations/อินฟลูเอนเซอร์": require("./Occupations/อินฟลูเอนเซอร์.png"),
  "Occupations/เจ้าหน้าที่สิ่งแวดล้อม": require("./Occupations/เจ้าหน้าที่สิ่งแวดล้อม.png"),
  "Occupations/แฮกเกอร์": require("./Occupations/แฮกเกอร์.png"),
  "Places/ตลาด": require("./Places/ตลาด.png"),
  "Places/ถนน": require("./Places/ถนน.png"),
  "Places/ทะเล": require("./Places/ทะเล.png"),
  "Places/บ้าน": require("./Places/บ้าน.png"),
  "Places/ภูเขา": require("./Places/ภูเขา.png"),
  "Places/รถไฟ": require("./Places/รถไฟ.png"),
  "Places/ร้านกาแฟ": require("./Places/ร้านกาแฟ.png"),
  "Places/ร้านอาหาร": require("./Places/ร้านอาหาร.png"),
  "Places/วัด": require("./Places/วัด.png"),
  "Places/สนามบิน": require("./Places/สนามบิน.jpg"),
  "Places/สวนสาธารณะ": require("./Places/สวนสาธารณะ.jpg"),
  "Places/ห้องครัว": require("./Places/ห้องครัว.png"),
  "Places/ห้องน้ำ": require("./Places/ห้องน้ำ.png"),
  "Places/ห้องเรียน": require("./Places/ห้องเรียน.jpg"),
  "Places/โรงพยาบาล": require("./Places/โรงพยาบาล.png"),
  "Places/โรงเรียน": require("./Places/โรงเรียน.png"),
  "Technology/กล้อง": require("./Technology/กล้อง.png"),
  "Technology/คอมพิวเตอร์": require("./Technology/คอมพิวเตอร์.png"),
  "Technology/คีย์บอร์ด": require("./Technology/คีย์บอร์ด.png"),
  "Technology/ปุ่ม": require("./Technology/ปุ่ม.png"),
  "Technology/มือถือ": require("./Technology/มือถือ.png"),
  "Technology/รหัสผ่าน": require("./Technology/รหัสผ่าน.png"),
  "Technology/หูฟัง": require("./Technology/หูฟัง.png"),
  "Technology/อินเทอร์เน็ต": require("./Technology/อินเทอร์เน็ต.png"),
  "Technology/อีเมล": require("./Technology/อีเมล.png"),
  "Technology/เกม": require("./Technology/เกม.png"),
  "Technology/เมาส์": require("./Technology/เมาส์.png"),
  "Technology/เว็บไซต์": require("./Technology/เว็บไซต์.png"),
  "Technology/แอป": require("./Technology/แอป.png"),
  "Technology/โน๊คบุ๊ก": require("./Technology/โน๊คบุ๊ก.png"),
  "Technology/โปรเเกรม": require("./Technology/โปรเเกรม.png"),
  "Technology/ไมโครโฟน": require("./Technology/ไมโครโฟน.png"),
  "Time/กลางคืน": require("./Time/กลางคืน.png"),
  "Time/ชั่วโมง": require("./Time/ชั่วโมง.png"),
  "Time/ตอนนี้": require("./Time/ตอนนี้.png"),
  "Time/นาที": require("./Time/นาที.png"),
  "Time/บ่าย": require("./Time/บ่าย.png"),
  "Time/ปี": require("./Time/ปี.png"),
  "Time/พรุ่งนี้": require("./Time/พรุ่งนี้.png"),
  "Time/ฤดูฝน": require("./Time/ฤดูฝน.png"),
  "Time/ฤดูร้อน": require("./Time/ฤดูร้อน.png"),
  "Time/ฤดูหนาว": require("./Time/ฤดูหนาว.png"),
  "Time/วัน": require("./Time/วัน.png"),
  "Time/วันนี้": require("./Time/วันนี้.png"),
  "Time/วินาที": require("./Time/วินาที.png"),
  "Time/เช้า": require("./Time/เช้า.png"),
  "Time/เดือน": require("./Time/เดือน.png"),
  "Time/เที่ยง": require("./Time/เที่ยง.png"),
  "Time/เมื่อวาน": require("./Time/เมื่อวาน.png"),
  "Time/เย็น": require("./Time/เย็น.png"),
  "Transportation/จักรยาน": require("./Transportation/จักรยาน.png"),
  "Transportation/ถนน": require("./Transportation/ถนน.png"),
  "Transportation/ทางม้าลาย": require("./Transportation/ทางม้าลาย.png"),
  "Transportation/ป้ายรถเมล์": require("./Transportation/ป้ายรถเมล์.png"),
  "Transportation/มอเตอร์ไซค์": require("./Transportation/มอเตอร์ไซค์.png"),
  "Transportation/รถบัส": require("./Transportation/รถบัส.png"),
  "Transportation/รถยนต์": require("./Transportation/รถยนต์.png"),
  "Transportation/รถแท็กซี่": require("./Transportation/รถแท็กซี่.png"),
  "Transportation/รถไฟ": require("./Transportation/รถไฟ.png"),
  "Transportation/รถไฟฟ้า": require("./Transportation/รถไฟฟ้า.png"),
  "Transportation/สะพาน": require("./Transportation/สะพาน.png"),
  "Transportation/สัญญาณไฟ": require("./Transportation/สัญญาณไฟ.png"),
  "Transportation/เครื่องบิน": require("./Transportation/เครื่องบิน.png"),
  "Transportation/เรือ": require("./Transportation/เรือ.png"),
  "Transportation/แยก": require("./Transportation/แยก.png"),
  "Weather/ฝน": require("./Weather/ฝน.png"),
  "Weather/พายุ": require("./Weather/พายุ.png"),
  "Weather/ฟ้า": require("./Weather/ฟ้า.png"),
  "Weather/ฟ้าผ่า": require("./Weather/ฟ้าผ่า.png"),
  "Weather/ร้อน": require("./Weather/ร้อน.png"),
  "Weather/ลม": require("./Weather/ลม.png"),
  "Weather/หนาว": require("./Weather/หนาว.png"),
  "Weather/หมอก": require("./Weather/หมอก.png"),
  "Weather/หิมะ": require("./Weather/หิมะ.png"),
  "Weather/อบอุ่น": require("./Weather/อบอุ่น.png"),
  "Weather/อุณหภูมิ": require("./Weather/อุณหภูมิ.png"),
  "Weather/เมฆ": require("./Weather/เมฆ.png"),
  "Weather/แดด": require("./Weather/แดด.png"),
  "picture/airplane": require("./picture/airplane.png"),
  "picture/boat": require("./picture/boat.png"),
  "picture/cold": require("./picture/cold.png"),
  "picture/father": require("./picture/father.png"),
  "picture/green": require("./picture/green.png"),
  "picture/hospital": require("./picture/hospital.png"),
  "picture/house": require("./picture/house.png"),
  "picture/market": require("./picture/market.png"),
  "picture/mother": require("./picture/mother.png"),
  "picture/rain": require("./picture/rain.png"),
  "picture/red": require("./picture/red.png"),
  "picture/rice": require("./picture/rice.png"),
  "picture/school": require("./picture/school.png"),
  "picture/skyblue": require("./picture/skyblue.png"),
  "picture/sun": require("./picture/sun.png"),
  "picture/water": require("./picture/water.png"),
  "picture/แมวเสร็จภารกิจ": require("./picture/แมวเสร็จภารกิจ.png"),
};

export default ADD_IMAGES;