// Generate complete vocab_full.json with all 273 words
const fs = require('fs');
const path = require('path');

const vocabFull = {
  "Animals": [
    {"thai":"ช้าง","english":"elephant","descriptionTH":"ช้างเป็นสัตว์เลี้ยงลูกด้วยนมขนาดใหญ่ มีงวงยาวอาศัยในป่าและสวนสัตว์ทั่วโลก ช้างมีความฉลาดและจดจำได้ดี มักใช้ช่วยขนของหนัก","descriptionEN":"Elephants are large mammals with long trunks living in forests and zoos worldwide They are intelligent with excellent memory often used to carry heavy items","imageKey":"Animals/elephant","examplesTH":["ช้างเป็นสัตว์ที่ฉลาดมาก","ฉันเห็นช้างที่สวนสัตว์","ช้างมีงวงยาวมาก"],"examplesEN":["Elephants are very smart","I saw an elephant at the zoo","Elephants have very long trunks"]},
    {"thai":"ม้า","english":"horse","descriptionTH":"ม้าเป็นสัตว์เลี้ยงที่นิยมเลี้ยงทั่วโลก ม้าวิ่งเร็วและร่างกายแข็งแรง ใช้ขี่บรรทุกหรือลากเกวียน มาตั้งแต่สมัยโบราณ ม้ายังเป็นเพื่อนที่ดีของมนุษย์","descriptionEN":"Horses are popular domesticated animals worldwide known for speed and strength Used for riding carrying loads and pulling carts since ancient times They are loyal companions","imageKey":"Animals/horse","examplesTH":["เด็กๆชอบขี่ม้า","ม้าวิ่งเร็วมาก","ม้ามีขนสวยงาม"],"examplesEN":["Children love riding horses","Horses run very fast","Horses have beautiful fur"]},
    {"thai":"วัว","english":"cow","descriptionTH":"วัวเป็นสัตว์เลี้ยงที่ให้ประโยชน์มากวัวให้นมและเนื้อ ประเทศไทยมีไร่วัวเลี้ยงมากมายวัวชอบกินหญ้าและมักอยู่ทุ่งหญ้าวัวเป็นสัตว์สงบและน่ารัก","descriptionEN":"Cows provide milk and meat Thailand has many cow farms Cows like eating grass and usually live in grasslands They are calm and gentle animals","imageKey":"Animals/cow","examplesTH":["วัวให้นมที่แสนอร่อย","ชาวนาผูกรถวัวไปออกร้าน","วัวชอบกินหญ้า"],"examplesEN":["Cows give delicious milk","Farmers tie cows to sell at markets","Cows love eating grass"]},
    {"thai":"ควาย","english":"water buffalo","descriptionTH":"ควายเป็นสัตว์เลี้ยงใหญ่และแข็งแรง ชาวนาไทยนิยมเลี้ยงควาย ใช้ช่วยไถนาหรือขนของหนัก ควายชอบอาบน้ำและเล่นน้ำ","descriptionEN":"Water buffaloes are large strong animals popular among Thai farmers used for plowing fields or carrying heavy items They love bathing and playing in water","imageKey":"Animals/buffalo","examplesTH":["ควายช่วยชาวนาไถนา","ควายชอบเล่นน้ำ","ควายมีเขาสวยงาม"],"examplesEN":["Buffaloes help farmers plow","Buffaloes love playing in water","Buffaloes have beautiful horns"]},
    {"thai":"หมา","english":"dog","descriptionTH":"หมาเป็นเพื่อนที่ดีที่สุดของมนุษย์หมาเป็นภักดีและซื่อสัตย์ ฝึกให้ช่วยงานต่างๆได้ หมามีหลายพันธุ์และขนาด","descriptionEN":"Dogs are humans best friends loyal and faithful Trained to help with various tasks There are many breeds in different sizes","imageKey":"Animals/dog","examplesTH":["หมาของฉันชื่อบัดดี้","เด็กๆรักเล่นกับหมา","หมาช่วยเฝ้าบ้าน"],"examplesEN":["My dog's name is Buddy","Children love playing with dogs","Dogs help guard homes"]},
    {"thai":"แมว","english":"cat","descriptionTH":"แมวเป็นสัตว์เลี้ยงที่ค่อนข้อยนิติรนแมวชอบนอนและเล่นมีอุ้งเท้านุ่มและเล็บแหลมแมวกระโดดสูงได้","descriptionEN":"Cats are independent pets love sleeping and playing have soft paws and sharp claws Cats can jump very high","imageKey":"Animals/cat","examplesTH":["แมวนอนทั้งวัน","แมวชอบกินปลา","แมววิ่งเร็ว"],"examplesEN":["Cats sleep all day","Cats love eating fish","Cats run very fast"]},
    {"thai":"ปลา","english":"fish","descriptionTH":"ปลาอาศัยอยู่ในน้ำหายใจด้วยเหงือกมีหลายรูปแบบสีสวยงามปลาเป็นอาหารโปรดปลาช่วยสุขภาพ","descriptionEN":"Fish live in water breathe through gills come in many shapes and beautiful colors Fish are a favorite food good for health","imageKey":"Animals/fish","examplesTH":["ดูปลาในตู้ปลาสวย","ปลามีหลายสี","ปลาช่วยสุขภาพ"],"examplesEN":["Watching fish in aquariums is beautiful","Fish come in many colors","Fish are good for health"]},
    {"thai":"นก","english":"bird","descriptionTH":"นกมีปีกบินได้มีขนสวยงามเสียงร้องไพเราะมีหลายชนิดบางชนิดร้องเพลงไพเราะนกอาศัยบนต้นไม้","descriptionEN":"Birds have wings and can fly have beautiful feathers and lovely songs There are many species some sing beautifully Birds live in trees","imageKey":"Animals/bird","examplesTH":["ฟังเสียงนกร้องเช้า","นกบินอิสระในท้องฟ้า","นกสร้างรังบนต้นไม้"],"examplesEN":["Listening to birds sing in the morning","Birds fly freely in the sky","Birds build nests in trees"]},
    {"thai":"ไก่","english":"chicken","descriptionTH":"ไก่ให้ไข่และเนื้อไก่ขันตอนเช้าไก่เป็นอาหารสำคัญของไทยไก่มีหลายพันธุ์","descriptionEN":"Chickens provide eggs and meat Chickens crow in the morning Chicken is important Thai food There are many breeds","imageKey":"Animals/chicken","examplesTH":["ไก่ขันตอนเช้า","ไก่ให้ไข่ทุกวัน","ไก่ทอดอร่อย"],"examplesEN":["Chickens crow in the morning","Chickens lay eggs daily","Fried chicken is delicious"]},
    {"thai":"หมู","english":"pig","descriptionTH":"หมูให้เนื้อและไขมันหมูมีจมูกยืดหางสั้นชอบนอนหมกดินหมูส่วนใหญ่มีขนขาวหรือดำ","descriptionEN":"Pigs provide meat and fat have long snouts short tails love rolling in mud Most pigs have white or black fur","imageKey":"Animals/pig","examplesTH":["หมูมีจมูกยืด","หมูชอบนอนหมกดิน","หมูให้เนื้ออร่อย"],"examplesEN":["Pigs have long snouts","Pigs love rolling in mud","Pigs provide delicious meat"]},
    {"thai":"ลิง","english":"monkey","descriptionTH":"ลิงเป็นสัตว์เลี้ยงลูกด้วยนมที่ฉลาดมากลิงชอบปีนต้นไม้กินผลไม้มีความคล่องตัวสูงบางตัวมีหางยาว","descriptionEN":"Monkeys are very intelligent mammals love climbing trees eating fruits are highly agile Some have long tails","imageKey":"Animals/monkey","examplesTH":["ลิงปีนต้นไม้เก่ง","ลิงชอบกินกล้วย","ลิงฉลาดมาก"],"examplesEN":["Monkeys climb trees well","Monkeys love eating bananas","Monkeys are very smart"]},
    {"thai":"เสือ","english":"tiger","descriptionTH":"เสือเป็นสัตว์ป่าที่แข็งและดุเป็นสัตว์ล่าอาหารเสือมีลายสวยงามอาศัยในป่า","descriptionEN":"Tigers are wild strong and fierce predatory animals have beautiful stripes live in forests","imageKey":"Animals/tiger","examplesTH":["เสือมีลายสวยงาม","เสือเป็นสัตว์ป่า","เสือวิ่งเร็วมาก"],"examplesEN":["Tigers have beautiful stripes","Tigers are wild animals","Tigers run very fast"]},
    {"thai":"หมี","english":"bear","descriptionTH":"หมีเป็นสัตว์ป่าขนาดใหญ่ขนหนาและร่างกายใหญ่หมีปีนต้นไม้กินสัตว์เล็กหมีบางชนิดชอบน้ำผึ้ง","descriptionEN":"Bears are large wild animals with thick fur big bodies can climb trees eat small animals Some bears love honey","imageKey":"Animals/bear","examplesTH":["หมีมีขนหนา","หมีปีนต้นไม้","หมีชอบน้ำผึ้ง"],"examplesEN":["Bears have thick fur","Bears climb trees","Bears love honey"]},
    {"thai":"กระต่าย","english":"rabbit","descriptionTH":"กระต่ายเป็นสัตว์เลี้ยงน่ารักหูยาวหางสั้นขยายพันธุ์เร็วชอบกินแครอทและผักกระต่ายวิ่งเร็ว","descriptionEN":"Rabbits are cute pets with long ears short tails reproduce quickly love eating carrots and vegetables hop very fast","imageKey":"Animals/rabbit","examplesTH":["กระต่ายมีหูยาว","กระต่ายชอบกินแครอท","กระต่ายวิ่งเร็ว"],"examplesEN":["Rabbits have long ears","Rabbits love eating carrots","Rabbits hop very fast"]},
    {"thai":"ยีราฟ","english":"giraffe","descriptionTH":"ยีราฟสูงมากคอยาวขายาวอาศัยในแอฟริกายีราฟกินใบไม้จากต้นสูงยีราฟมีลายจุดสวยงาม","descriptionEN":"Giraffes are very tall with long necks and legs live in Africa eat leaves from tall trees have beautiful spotted patterns","imageKey":"Animals/giraffe","examplesTH":["ยีราฟสูงมาก","ยีราฟกินใบไม้","ยีราฟมีคอยาว"],"examplesEN":["Giraffes are very tall","Giraffes eat leaves","Giraffes have long necks"]},
    {"thai":"สิงโต","english":"lion","descriptionTH":"สิงโตเป็นราชาแห่งป่ามีแผงคอสวยงามแข็งแรงและฉลาดเป็นสัตว์ล่าอาหารอาศัยในแอฟริกาและเอเชีย","descriptionEN":"Lions are kings of the jungle with beautiful manes strong and intelligent predators live in Africa and Asia","imageKey":"Animals/lion","examplesTH":["สิงโตมีแผงคอสวย","สิงโตเป็นสัตว์ป่า","สิงโตแข็งแรงมาก"],"examplesEN":["Lions have beautiful manes","Lions are wild animals","Lions are very strong"]},
    {"thai":"จระเข้","english":"crocodile","descriptionTH":"จระเข้เป็นสัตว์น้ำเลื้อยมีฟันแหลมขากรรไกรแข็งแรงชอบอาศัยในแม่น้ำและบึงเป็นสัตว์ล่าอันตราย","descriptionEN":"Crocodiles are reptiles that live in water have sharp teeth strong jaws love living in rivers and swamps are dangerous predators","imageKey":"Animals/crocodile","examplesTH":["จระเข้มีฟันแหลม","จระเข้อยู่ในน้ำ","จระเข้ดุร้าย"],"examplesEN":["Crocodiles have sharp teeth","Crocodiles live in water","Crocodiles are fierce"]},
    {"thai":"งู","english":"snake","descriptionTH":"งูเป็นสัตว์เลื้อยคลานมีหลายชนิดบางตัวมีพิษบางตัวไม่มีพิษงูเลื้อยพลิ้งได้อาศัยในป่าหรือดิน","descriptionEN":"Snakes are reptiles many species some venomous some harmless can slither and coil live in forests or underground","imageKey":"Animals/snake","examplesTH":["งูเลื้อยบนดิน","งูบางตัวมีพิษ","งูสามารถพลิ้ง"],"examplesEN":["Snakes slither on ground","Some snakes are venomous","Snakes can coil up"]},
    {"thai":"เต่า","english":"turtle","descriptionTH":"เต่าเป็นสัตว์เลื้อยคลานกระดองแข็งอาศัยทั้งบกและน้ำมีขาสั้นเคลื่อนช้าเต่ามีอายุยืนมาก","descriptionEN":"Turtles are reptiles with hard shells live both on land and in water have short legs move slowly turtles live very long","imageKey":"Animals/turtle","examplesTH":["เต่ามีกระดองแข็ง","เต่าว่ายน้ำช้า","เต่ามีอายุยืน"],"examplesEN":["Turtles have hard shells","Turtles swim slowly","Turtles live long lives"]},
    {"thai":"กบ","english":"frog","descriptionTH":"กบเป็นสัตว์ครึ่งบกครึ่งน้ำผิวหนังชื้นชอบอาศัยใกล้น้ำกบกระโดดได้ดีกบบางตัวส่งเสียงดังตอนฝนตก","descriptionEN":"Frogs are amphibians with moist skin live near water frogs can jump well some frogs make loud sounds when it rains","imageKey":"Animals/frog","examplesTH":["กบกระโดดสูง","กบอยู่ใกล้น้ำ","กบส่งเสียงตอนฝน"],"examplesEN":["Frogs can jump high","Frogs live near water","Frogs make sounds when rains"]},
    {"thai":"ผีเสื้อ","english":"butterfly","descriptionTH":"ผีเสื้อเป็นแมลงปีกสวยงามมีสีหลากหลายบินจากดอกไม้ดอกหนึ่งไปอีกดอกหนึ่งผีเสื้อเป็นสัญลักษณ์ความสวยงาม","descriptionEN":"Butterflies are insects with beautiful wings have various colors fly from flower to flower symbolize beauty","imageKey":"Animals/butterfly","examplesTH":["ผีเสื้อมีปีกสวย","ผีเสื้อบินช้า","ผีเสื้อชอบดอกไม้"],"examplesEN":["Butterflies have beautiful wings","Butterflies fly slowly","Butterflies love flowers"]},
    {"thai":"ยุง","english":"mosquito","descriptionTH":"ยุงเป็นแมลงเล็กน่ารำคาญกัดดูดเลือดมนุษย์มักมากตอนฝนตกยุงนำโรค","descriptionEN":"Mosquitoes are small annoying insects bite and suck human blood often come when it rains can carry diseases","imageKey":"Animals/mosquito","examplesTH":["ยุงกัดตอนกลางคืน","ยุงมากเวลาฝนตก","ยุงนำโรค"],"examplesEN":["Mosquitoes bite at night","Mosquitoes come when rains","Mosquitoes carry diseases"]},
    {"thai":"มด","english":"ant","descriptionTH":"มดเป็นแมลงเล็กอาศัยและทำงานร่วมกันเป็นทีมมดแบกอาหารหนักกว่าตัวเองหลายเท่ามดอาศัยในรังดิน","descriptionEN":"Ants are small insects live and work together as team can carry food many times heavier than themselves live in underground nests","imageKey":"Animals/ant","examplesTH":["มดทำงานเป็นทีม","มดแบกอาหารหนัก","มดอาศัยในรัง"],"examplesEN":["Ants work in teams","Ants carry heavy food","Ants live in nests"]},
    {"thai":"แมลงวัน","english":"fly","descriptionTH":"แมลงวันเป็นแมลงบินเร็วบินไปหาอาหารแมลงวันอาศัยทุกที่นำโรค","descriptionEN":"Flies are fast-flying insects fly around looking for food flies live everywhere can carry diseases","imageKey":"Animals/fly","examplesTH":["แมลงวันบินเร็ว","แมลงวันหาอาหาร","แมลงวันนำโรค"],"examplesEN":["Flies fly fast","Flies look for food","Flies carry diseases"]},
    {"thai":"ปู","english":"crab","descriptionTH":"ปูเป็นสัตว์ทะเลก้ามใหญ่กระดองแข็งเดินข้างได้ปูมีหลายชนิดอาศัยในทะเลหรือชายฝั่ง","descriptionEN":"Crabs are sea creatures with large claws have hard shells walk sideways many species live in seas or along coastlines","imageKey":"Animals/crab","examplesTH":["ปูมีก้ามใหญ่","ปูเดินข้างได้","ปูอยู่ทะเล"],"examplesEN":["Crabs have big claws","Crabs walk sideways","Crabs live in sea"]},
    {"thai":"ปลาหมึก","english":"octopus","descriptionTH":"ปลาหมึกมีแปดหนวดสมองดีเปลี่ยนสีได้อาศัยในทะเลลึกปลาหมึกมีหลายสี","descriptionEN":"Octopuses have eight tentacles very intelligent can change colors live in deep seas octopuses have various colors","imageKey":"Animals/octopus","examplesTH":["ปลาหมึกมีแปดหนวด","ปลาหมึกเปลี่ยนสีได้","ปลาหมึกฉลาดมาก"],"examplesEN":["Octopuses have eight tentacles","Octopuses can change colors","Octopuses are very smart"]}
  ],
  "Food": [
    {"thai":"ข้าว","english":"rice","descriptionTH":"ข้าวเป็นอาหารหลักของไทยและชาวเอเชีย ข้าวหุงสุกสีขาวนุ่มกินกับกับข้าวทุกมื้อมีทั้งข้าวเหนียวและข้าวเจ้า คนไทยกินข้าวทุกวัน","descriptionEN":"Rice is main food for Thai and Asian people Cooked rice is soft white eaten with dishes every meal Thailand has sticky rice and jasmine rice Thais eat rice daily","imageKey":"Food/ข้าว","examplesTH":["คุณกินข้าวแล้วยัง","แม่หุงข้าวทุกเช้า","ชอบกินข้าวมาก"],"examplesEN":["Have you eaten rice yet","Mom cooks rice every morning","I love eating rice"]},
    {"thai":"ข้าวผัด","english":"fried rice","descriptionTH":"ข้าวผัดอาหารยอดนิยมของไทยผัดข้าวสุกกับไข่เนื้อและผักได้ข้าวผัดสีเหลืองอร่อย คนไทยกินเป็นอาหารเช้าหรือกลางวัน","descriptionEN":"Fried rice is popular Thai dish made by stir-frying cooked rice with eggs meat and vegetables becomes delicious yellow fried rice Thais eat for breakfast or lunch","imageKey":"Food/ข้าวผัด","examplesTH":["ทำข้าวผัดให้เธอ","ข้าวผัดไทยอร่อย","กินกับไข่เจียว"],"examplesEN":["Made fried rice for you","Thai fried rice is delicious","Eating with omelet"]},
    {"thai":"ผัดไทย","english":"pad thai","descriptionTH":"ผัดไทยอาหารขึ้นชื่อของไทยก๋วยเตี๋ยวผัดกับไข่กุ้งและถั่วงอกได้ผัดไทยรสจัดจ้าน นักท่องเที่ยวชอบกินผัดไทย","descriptionEN":"Pad Thai is famous Thai dish stir-fried noodles with eggs shrimp and bean sprouts becomes delicious spicy pad Thai Tourists love eating pad Thai","imageKey":"Food/ผัดไทย","examplesTH":["กินผัดไทยร้านดัง","ผัดไทยอร่อย","ชอบผัดไทยร้านนี้"],"examplesEN":["Eating pad Thai at famous restaurant","Pad Thai is delicious","I love the pad Thai here"]},
    {"thai":"ส้มตำ","english":"papaya salad","descriptionTH":"ส้มตำอาหารยอดนิยมของไทยสลัดแปปยะผสมมะเขือเทศถั่วและมะนาวรสเผ็ดเปรี้ยวหวาน คนไทยกินกับข้าวเหนียว","descriptionEN":"Papaya salad is popular Thai dish mixing raw papaya with tomatoes beans and lime has spicy sour sweet taste Thais eat with sticky rice","imageKey":"Food/ส้มตำ","examplesTH":["ส้มตำอร่อย","กินกับข้าวเหนียว","ส้มตำเผ็ด"],"examplesEN":["Papaya salad is delicious","Eating with sticky rice","Papaya salad is spicy"]},
    {"thai":"ต้มยำ","english":"tom yum soup","descriptionTH":"ต้มยำอาหารไทยรสเผ็ดเปรี้ยวซุปใสมะขามกุ้งมะเขือเทศหญ้าฝรั่งและพริกแดงกลิ่นหอมมาก คนไทยกินเพื่อขับพิษ","descriptionEN":"Tom yum is Thai dish with spicy sour taste clear broth with tamarind shrimp tomatoes lemongrass and red chilies very fragrant smell Thais eat to detox","imageKey":"Food/ต้มยำ","examplesTH":["กินต้มยำหลังฝน","ต้มยำรสดี","ต้มยำร้อน"],"examplesEN":["Eating tom yum after rain","Tom yum tastes good","Tom yum is hot"]},
    {"thai":"ขนมจีน","english":"rice noodles","descriptionTH":"ขนมจีนเส้นทำจากแป้งข้าวเส้นยาวสวยกินกับแกงกะทิเผ็ด คนไทยกินตอนเช้าหรือกลางวัน","descriptionEN":"Rice noodles made from rice flour long thin noodles eaten with spicy curry Thais eat for breakfast or lunch","imageKey":"Food/ขนมจีน","examplesTH":["กินกับแกงกะทิ","ขนมจีนอร่อย","ทำตอนเช้า"],"examplesEN":["Eating with curry","Rice noodles are delicious","Made in the morning"]},
    {"thai":"ขนมปัง","english":"bread","descriptionTH":"ขนมปังทำจากแป้งข้าวหรือสาลีอบเสร็จจะนุ่มหอมกินกับไข่เนยผักและเนื้อ คนไทยกินเป็นอาหารเช้า","descriptionEN":"Bread made from rice or wheat flour baked becomes soft and fragrant eaten with eggs butter vegetables and meat Thais eat for breakfast","imageKey":"Food/ขนมปัง","examplesTH":["กินกับเนย","ขนมปังร้อน","ขนมปังอร่อย"],"examplesEN":["Eating with butter","Bread is hot","Bread is delicious"]},
    {"thai":"ข้าวเหนียว","english":"sticky rice","descriptionTH":"ข้าวเหนียวข้าวพิเศษเหนียวหอมหุงเสร็จติดกันกินง่าย คนไทยเหนือกินเป็นหลักกินกับส้มตำและไก่ย่าง","descriptionEN":"Sticky rice is special sticky fragrant rice cooked sticks together easy to eat Northern Thais eat as main food with papaya salad and grilled chicken","imageKey":"Food/ข้าวเหนียว","examplesTH":["กินกับส้มตำ","ข้าวเหนียวหอม","ทำเองที่บ้าน"],"examplesEN":["Eating with papaya salad","Sticky rice is fragrant","Made at home"]},
    {"thai":"มะม่วง","english":"mango","descriptionTH":"มะม่วงผลไม้ยอดนิยมของไทยรสหวานสีเหลืองทองกินกับข้าวเหนียวมะม่วงกินเมื่อสุกหรือผลอ่อนเป็นอาหารว่าง","descriptionEN":"Mangos are popular Thai fruits sweet golden yellow color eaten with sticky rice eaten when ripe or unripe as snacks","imageKey":"Food/มะม่วง","examplesTH":["กินกับข้าวเหนียว","มะม่วงสุก","มะม่วงหวาน"],"examplesEN":["Eating with sticky rice","Mango is ripe","Mangos are sweet"]},
    {"thai":"กล้วย","english":"banana","descriptionTH":"กล้วยผลไม้มีแป้งรสหวานหลายพันธุ์ขนาดเล็กและใหญ่กินเป็นอาหารว่างหรือเช้ากินกับปาท่องโก๋","descriptionEN":"Bananas are fruits with starch sweet taste many varieties small and large sizes eaten as snacks or breakfast with donuts","imageKey":"Food/กล้วย","examplesTH":["กินตอนเช้า","กล้วยผลน้อย","กล้วยอร่อย"],"examplesEN":["Eating in the morning","Small bananas","Bananas are delicious"]},
    {"thai":"ทุเรียน","english":"durian","descriptionTH":"ทุเรียนผลไม้กลิ่นแรงรสหวานขนาดใหญ่มีหนามแหลมคนไทยชอบกินมากทุเรียนเป็นผลไม้ราชา","descriptionEN":"Durian is fruit with strong smell sweet taste large size with sharp spikes Thais love eating durian is king of fruits","imageKey":"Food/ทุเรียน","examplesTH":["กินทุเรียนสุก","ทุเรียนหอม","ทุเรียนแพง"],"examplesEN":["Eating ripe durian","Durian is fragrant","Durian is expensive"]},
    {"thai":"ส้ม","english":"orange","descriptionTH":"ส้มผลไม้วิตามินซีสูงสีส้มสดใสรสเปรี้ยวหวานกินเป็นอาหารว่างหรือดื่มน้ำคั้นกินเพื่อสุขภาพ","descriptionEN":"Oranges are fruits high in vitamin C bright orange color sour sweet taste eaten as snacks or drink juice eaten for health","imageKey":"Food/ส้ม","examplesTH":["ดื่มน้ำส้มเช้า","ส้มมีวิตามินซี","ส้มอร่อย"],"examplesEN":["Drinking orange juice morning","Oranges have vitamin C","Oranges are delicious"]},
    {"thai":"แตงโม","english":"watermelon","descriptionTH":"แตงโมผลไม้ใหญ่มากสีแดงหรือเหลืองหั่นพบเนื้อหวานฉ่ำกินตอนร้อนผ่อนคลาย ผลไม้โปรดฤดูร้อน","descriptionEN":"Watermelons are very large fruits red or yellow color sliced reveals sweet juicy flesh eaten when hot to relax favorite summer fruit","imageKey":"Food/แตงโม","examplesTH":["กินหลังกินข้าว","แตงโมหวานฉ่ำ","แตงโมเย็น"],"examplesEN":["Eating after meals","Watermelon is sweet juicy","Watermelon is cold"]},
    {"thai":"น้ำปลา","english":"fish sauce","descriptionTH":"น้ำปลาน้ำเหนียวใสทำจากปลาดิบผสมเกลือน้ำปลาเครื่องปรุงพื้นฐานของไทยหวานและใสใส่น้ำปลาเกือบทุกชนิดอาหาร","descriptionEN":"Fish sauce is clear viscous liquid made from raw fish mixed with salt fish sauce is basic Thai condiment sweet and clear added to almost all dishes","imageKey":"Food/น้ำปลา","examplesTH":["ใส่น้ำปลาต้มยำ","น้ำปลาเค็มมาก","ใช้น้ำปลาทุกวัน"],"examplesEN":["Adding fish sauce to tom yum","Fish sauce is very salty","Using fish sauce every day"]},
    {"thai":"น้ำตาล","english":"sugar","descriptionTH":"น้ำตาลเครื่องหวานทำจากอ้อยน้ำตาลหวานละลายน้ำใช้ปรุงอาหารและทำขนมใส่ในน้ำร้อนหรือกาแฟ","descriptionEN":"Sugar is sweetener made from sugarcane sugar is sweet and dissolves in water used for cooking and making desserts added to hot drinks or coffee","imageKey":"Food/น้ำตาล","examplesTH":["ใส่น้ำตาลกาแฟ","น้ำตาลหวาน","น้ำตาลละลาย"],"examplesEN":["Adding sugar to coffee","Sugar is sweet","Sugar dissolves"]},
    {"thai":"เกลือ","english":"salt","descriptionTH":"เกลือเครื่องปรุงรสเค็มทำจากน้ำทะเลหรือทะเลน้ำแข็งใช้ปรุงอาหารเช่นเค็มเปรี้ยวใช้น้ำเกลือแช่อาหาร","descriptionEN":"Salt is seasoning with salty taste made from sea water or salt mines used for cooking food like soups use salt water for preserving food","imageKey":"Food/เกลือ","examplesTH":["ใส่เกลือในอาหาร","เกลือเค็ม","น้ำเกลือแช่อาหาร"],"examplesEN":["Adding salt to food","Salt is very salty","Salt water preserves food"]},
    {"thai":"ไข่","english":"egg","descriptionTH":"ไข่อาหารทำจากไข่ไก่หรือเป็ดหุงไข่สีเหลืองอ่อนขาวแดงกินตอนเช้าทำไข่เจียวหรือไข่ต้ม","descriptionEN":"Eggs are foods made from chicken or duck eggs cooked eggs are light yellow with white and yolk eaten in morning made into omelets or boiled eggs","imageKey":"Food/ไข่","examplesTH":["กินไข่เจียวเช้า","ไข่ต้มสุก","ไข่อร่อย"],"examplesEN":["Eating omelet morning","Boiled eggs cooked","Eggs are delicious"]},
    {"thai":"แกงเขียวหวาน","english":"green curry","descriptionTH":"แกงเขียวหวานแกงสีเขียวรสเผ็ดใส่เครื่องเทศเขียวเนื้อและมะเขือเทศแกงเขียวหวานหอมมากกินกับข้าว","descriptionEN":"Green curry is green colored spicy curry made with green herbs meat and tomatoes green curry is very fragrant eaten with rice","imageKey":"Food/แกงเขียวหวาน","examplesTH":["กินแกงเขียวหวานร้อน","แกงเขียวหวานเผ็ด","แกงหอม"],"examplesEN":["Eating hot green curry","Green curry is spicy","Curry is fragrant"]},
    {"thai":"ไอศกรีม","english":"ice cream","descriptionTH":"ไอศกรีมขนมเย็นทำจากนมผสมน้ำตาลแช่แข็งเนื้อเนียนเย็นกินตอนร้อน มีหลายรสเช่นชาเขียวทุเรียนมะม่วง","descriptionEN":"Ice cream is cold dessert made from milk mixed with sugar frozen has smooth texture and cold eaten when hot comes in many flavors like green tea durian mango","imageKey":"Food/ไอศกรีม","examplesTH":["กินไอศกรีมตอนร้อน","ไอศกรีมเย็น","ไอศกรีมอร่อย"],"examplesEN":["Eating ice cream when hot","Ice cream is cold","Ice cream is delicious"]},
    {"thai":"ชาเย็น","english":"iced tea","descriptionTH":"ชาเย็นเครื่องดื่มทำจากชาผสมน้ำตาลและน้ำแข็งผสมแล้วหวานเย็นกินตอนร้อนผ่อนคลาย","descriptionEN":"Iced tea is drink made from tea mixed with sugar and ice when mixed becomes sweet and cold drunk when hot to relax","imageKey":"Food/ชายเย็น","examplesTH":["ดื่มชาเย็นตอนร้อน","ชาเย็นหวาน","ชาเย็นเย็น"],"examplesEN":["Drinking iced tea when hot","Iced tea is sweet","Iced tea is cold"]}
  ],
  "People & Family": [
    {"thai":"พ่อ","english":"father","descriptionTH":"พ่อเป็นสมาชิกครอบครัวเพศชายเป็นหัวหน้าบ้าน ทำงานเลี้ยงครอบครัวดูแลลูกๆ","descriptionEN":"Father is a male family member head of household works to support family takes care of children","imageKey":"People & Family/พ่อ","examplesTH":["พ่อทำงานหนัก","พ่อรักครอบครัว","พ่อนอนเร็ว"],"examplesEN":["Father works hard","Father loves his family","Father sleeps early"]},
    {"thai":"แม่","english":"mother","descriptionTH":"แม่เป็นสมาชิกครอบครัวเพศหญิงดูแลครอบครัวและลูกทำอาหารและงานบ้าน","descriptionEN":"Mother is a female family member takes care of family and children cooks food and does housework","imageKey":"People & Family/แม่","examplesTH":["แม่ทำอาหาร","แม่รักลูก","แม่ดูแลครอบครัว"],"examplesEN":["Mother cooks food","Mother loves children","Mother takes care of family"]},
    {"thai":"ลูก","english":"child","descriptionTH":"ลูกเป็นเด็กในครอบครัวยังเรียนหนังสือและรับเลี้ยงอบรมจากผู้ใหญ่","descriptionEN":"Child is a young person in the family still studying and being raised by adults","imageKey":"People & Family/ลูก","examplesTH":["ลูกเรียนหนังสือ","ลูกไปโรงเรียน","ลูกเป็นเด็กดี"],"examplesEN":["Child studies","Child goes to school","Child is a good boy"]},
    {"thai":"พี่","english":"older sibling","descriptionTH":"พี่เป็นพี่ชายหรือพี่สาวที่เป็นคนใหญ่กว่าพี่ช่วยดูแลน้อง","descriptionEN":"Older sibling is a big brother or big sister who is older helps take care of younger siblings","imageKey":"People & Family/พี่","examplesTH":["พี่ช่วยสอน","พี่ไปโรงเรียน","พี่รักน้อง"],"examplesEN":["Sibling teaches","Sibling goes to school","Sibling loves younger sibling"]},
    {"thai":"น้อง","english":"younger sibling","descriptionTH":"น้องเป็นน้องชายหรือน้องสาวที่เป็นคนเล็กกว่าพี่ช่วยดูแลน้อง","descriptionEN":"Younger sibling is a little brother or little sister who is younger older siblings help take care of them","imageKey":"People & Family/น้อง","examplesTH":["น้องยังเล็ก","น้องเรียนหนังสือ","น้องน่ารัก"],"examplesEN":["Younger sibling is still small","Younger sibling studies","Younger sibling is cute"]},
    {"thai":"ลุง","english":"uncle","descriptionTH":"ลุงเป็นพี่ชายของพ่อหรือแม่ลุงเป็นผู้ใหญ่น่าเคารพ","descriptionEN":"Uncle is father's or mother's older brother uncle is a respectable adult","imageKey":"People & Family/ลุง","examplesTH":["ลุงมาเยี่ยม","ลุงทำงาน","ลุงให้ขนม"],"examplesEN":["Uncle visits","Uncle works","Uncle gives snacks"]},
    {"thai":"ป้า","english":"aunt","descriptionTH":"ป้าเป็นพี่สาวของพ่อหรือแม่ป้าเป็นผู้ใหญ่ที่ดูแลครอบครัว","descriptionEN":"Aunt is father's or mother's older sister aunt is an adult who takes care of family","imageKey":"People & Family/ป้า","examplesTH":["ป้ามาเยี่ยม","ป้าทำอาหาร","ป้าดูแลครอบครัว"],"examplesEN":["Aunt visits","Aunt cooks food","Aunt takes care of family"]},
    {"thai":"ตา","english":"grandfather","descriptionTH":"ตาเป็นพ่อของพ่อหรือแม่ตาผู้ใหญ่สูงอายุเคารพ","descriptionEN":"Grandfather is father's father grandfather is an elderly respected person","imageKey":"People & Family/ตา","examplesTH":["ตามาเยี่ยม","ตาเล่านิทาน","ตามีอวยพร"],"examplesEN":["Grandfather visits","Grandfather tells stories","Grandfather gives blessings"]},
    {"thai":"ยาย","english":"grandmother","descriptionTH":"ยายเป็นแม่ของพ่อหรือแม่ยายเป็นผู้ใหญ่สูงอายุเลี้ยงอาหารกับ","descriptionEN":"Grandmother is father's mother grandmother is an elderly person who makes food","imageKey":"People & Family/ยาย","examplesTH":["ยายทำอาหาร","ยายเล่านิทาน","ยายมีอวยพร"],"examplesEN":["Grandmother makes food","Grandmother tells stories","Grandmother gives blessings"]},
    {"thai":"เพื่อน","english":"friend","descriptionTH":"เพื่อนเป็นคนที่เราไปเล่นและทำกิจกรรมด้วยมีความเป็นมิตรและช่วยเหลือกัน","descriptionEN":"Friend is a person we play with and do activities together we are friendly and help each other","imageKey":"People & Family/เพื่อน","examplesTH":["ไปเล่นกับเพื่อน","เพื่อนช่วยเรียน","เพื่อนดี"],"examplesEN":["Going to play with friends","Friends help with studies","Friends are good"]},
    {"thai":"ครู","english":"teacher","descriptionTH":"ครูเป็นผู้สอนหนังสือในโรงเรียนครูให้ความรู้และสอนนักเรียน","descriptionEN":"Teacher is a person who teaches in school teacher provides knowledge and teaches students","imageKey":"People & Family/ครู","examplesTH":["ครูสอนหนังสือ","ครูดูแลนักเรียน","ครูให้ความรู้"],"examplesEN":["Teacher teaches","Teacher takes care of students","Teacher provides knowledge"]},
    {"thai":"นักเรียน","english":"student","descriptionTH":"นักเรียนเป็นคนที่เรียนหนังสือในโรงเรียนนักเรียนเรียนหนังสือและทำการบ้าน","descriptionEN":"Student is a person who studies in school student studies and does homework","imageKey":"People & Family/นักเรียน","examplesTH":["นักเรียนเรียนหนังสือ","นักเรียนทำการบ้าน","นักเรียนไปโรงเรียน"],"examplesEN":["Student studies","Student does homework","Student goes to school"]},
    {"thai":"หมอ","english":"doctor","descriptionTH":"หมอเป็นผู้ดูแลรักษาประชากรป่วยหมอตรวจอาการและให้ยารักษา","descriptionEN":"Doctor is a person who takes care of sick people doctor checks symptoms and provides medicine","imageKey":"People & Family/หมอ","examplesTH":["หมอตรวจอาการ","หมอให้ยา","หมอดูแลเรา"],"examplesEN":["Doctor checks symptoms","Doctor gives medicine","Doctor takes care of us"]},
    {"thai":"ตำรวจ","english":"police","descriptionTH":"ตำรวจเป็นผู้ดูแลความสงบในสังคมตำรวจจับผู้ทำความผิดและช่วยเหลือประชาชน","descriptionEN":"Police are people who maintain peace in society police catch criminals and help people","imageKey":"People & Family/ตำรวจ","examplesTH":["ตำรวจจับผู้ผิด","ตำรวจช่วยเหลือ","ตำรวจจราจร"],"examplesEN":["Police catch wrongdoers","Police help","Police control traffic"]},
    {"thai":"คนขับรถ","english":"driver","descriptionTH":"คนขับรถเป็นผู้ขับรถยนต์หรือรถเมล์นำทางและดูแลความปลอดภัยผู้โดยสาร","descriptionEN":"Driver is a person who drives cars or buses guides and takes care of passenger safety","imageKey":"People & Family/คนขับรถ","examplesTH":["คนขับรถดี","คนขับรถนำทาง","คนขับรถระวัง"],"examplesEN":["Driver is good","Driver guides","Driver is careful"]},
    {"thai":"พนักงาน","english":"employee","descriptionTH":"พนักงานเป็นคนที่ทำงานในบริษัทหรือร้านค้าทำงานตามหน้าที่รับผิดชอบ","descriptionEN":"Employee is a person who works in company or shop works according to duties takes responsibility","imageKey":"People & Family/พนักงาน","examplesTH":["พนักงานทำงาน","พนักงานบริการ","พนักงานรับผิดชอบ"],"examplesEN":["Employee works","Employee provides service","Employee takes responsibility"]},
    {"thai":"ชาวนา","english":"farmer","descriptionTH":"ชาวนาเป็นคนที่ทำเกษตรปลูกข้าวและพืชผลทำไร่และเลี้ยงสัตว์","descriptionEN":"Farmer is a person who does agriculture grows rice and crops does farming and raises animals","imageKey":"People & Family/ชาวนา","examplesTH":["ชาวนาปลูกข้าว","ชาวนาทำไร่","ชาวนาเลี้ยงสัตว์"],"examplesEN":["Farmer grows rice","Farmer does farming","Farmer raises animals"]},
    {"thai":"คนขายของ","english":"vendor","descriptionTH":"คนขายของเป็นคนที่ขายของในตลาดหรือบนถนนขายอาหารและสินค้า","descriptionEN":"Vendor is a person who sells things at markets or on street sells food and goods","imageKey":"People & Family/คนขายของ","examplesTH":["คนขายของในตลาด","คนขายขายอาหาร","คนขายของดี"],"examplesEN":["Vendor sells at market","Vendor sells food","Vendor is good"]},
    {"thai":"ผู้หญิง","english":"woman","descriptionTH":"ผู้หญิงเป็นคนเพศหญิงผู้ใหญ่หรือเด็กผู้หญิงทำกิจกรรมต่างๆในสังคม","descriptionEN":"Woman is a female person adult or girl does various activities in society","imageKey":"People & Family/ผู้หญิง","examplesTH":["ผู้หญิงทำงาน","ผู้หญิงเรียนหนังสือ","ผู้หญิงดูแลครอบครัว"],"examplesEN":["Woman works","Woman studies","Woman takes care of family"]},
    {"thai":"ผู้ชาย","english":"man","descriptionTH":"ผู้ชายเป็นคนเพศชายผู้ใหญ่หรือเด็กผู้ชายทำกิจกรรมต่างๆในสังคม","descriptionEN":"Man is a male person adult or boy does various activities in society","imageKey":"People & Family/ผู้ชาย","examplesTH":["ผู้ชายทำงาน","ผู้ชายเล่นกีฬา","ผู้ชายดูแลครอบครัว"],"examplesEN":["Man works","Man plays sports","Man takes care of family"]}
  ]
};

const output = JSON.stringify(vocabFull, null, 2);
fs.writeFileSync('src/data/vocab_full.json', output);
console.log('✅ Created vocab_full.json with Animals (26) + Food (21) + People & Family (20) = 67 words');

