const mongoose = require('mongoose');
const path = require('path');
const dotenv = require('dotenv');

dotenv.config({ path: path.join(__dirname, '../config.env') });

// Define Schema
const foodDrinksSchema = new mongoose.Schema({
  thai: String,
  roman: String,
  en: String,
  category: String,
  type: String,
  level: String,
  imageUrl: String,
  emoji: String,
  audioText: String,
  tags: [String],
  isActive: Boolean,
  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now },
}, { collection: 'food_drinks_vocab' });

const FoodDrinksVocab = mongoose.model('FoodDrinksVocab', foodDrinksSchema);

// Seed Data
const foodDrinksData = [
  {
    thai: 'ข้าวผัด',
    roman: 'khao phat',
    en: 'fried rice',
    category: 'thai-food',
    type: 'dish',
    level: 'Intermediate',
    imageUrl: '/assets/food_drinks/khao_phat.jpg',
    emoji: '🍚',
    audioText: 'ข้าวผัด',
    tags: ['popular', 'lunch'],
    isActive: true,
  },
  {
    thai: 'ผัดกะเพรา',
    roman: 'phat kaphrao',
    en: 'basil stir-fry',
    category: 'thai-food',
    type: 'dish',
    level: 'Intermediate',
    imageUrl: '/assets/food_drinks/phat_kaphrao.jpg',
    emoji: '🍛',
    audioText: 'ผัดกะเพรา',
    tags: ['spicy', 'popular'],
    isActive: true,
  },
  {
    thai: 'ต้มยำกุ้ง',
    roman: 'tom yam goong',
    en: 'tom yum shrimp',
    category: 'thai-food',
    type: 'dish',
    level: 'Intermediate',
    imageUrl: '/assets/food_drinks/tom_yam.jpg',
    emoji: '🍲',
    audioText: 'ต้มยำกุ้ง',
    tags: ['spicy', 'soup'],
    isActive: true,
  },
  {
    thai: 'ส้มตำ',
    roman: 'som tam',
    en: 'papaya salad',
    category: 'thai-food',
    type: 'dish',
    level: 'Intermediate',
    imageUrl: '/assets/food_drinks/somtam.jpg',
    emoji: '🥗',
    audioText: 'ส้มตำ',
    tags: ['spicy', 'northeast'],
    isActive: true,
  },
  {
    thai: 'ผัดไทย',
    roman: 'phat thai',
    en: 'pad thai',
    category: 'thai-food',
    type: 'dish',
    level: 'Intermediate',
    imageUrl: '/assets/food_drinks/phat_thai.jpg',
    emoji: '🍜',
    audioText: 'ผัดไทย',
    tags: ['popular', 'noodles'],
    isActive: true,
  },
  {
    thai: 'แกงเขียวหวาน',
    roman: 'kaeng khiao wan',
    en: 'green curry',
    category: 'thai-food',
    type: 'dish',
    level: 'Intermediate',
    imageUrl: '/assets/food_drinks/kaeng_khiao.jpg',
    emoji: '🍛',
    audioText: 'แกงเขียวหวาน',
    tags: ['spicy', 'curry'],
    isActive: true,
  },
  {
    thai: 'ข้าวมันไก่',
    roman: 'khao man gai',
    en: 'hainanese chicken rice',
    category: 'thai-food',
    type: 'dish',
    level: 'Intermediate',
    imageUrl: '/assets/food_drinks/khao_man_gai.jpg',
    emoji: '🍚',
    audioText: 'ข้าวมันไก่',
    tags: ['mild', 'popular'],
    isActive: true,
  },
  {
    thai: 'ก๋วยเตี๋ยว',
    roman: 'kuai tiao',
    en: 'noodles',
    category: 'thai-food',
    type: 'dish',
    level: 'Intermediate',
    imageUrl: '/assets/food_drinks/kuai_tiao.jpg',
    emoji: '🍲',
    audioText: 'ก๋วยเตี๋ยว',
    tags: ['noodles', 'popular'],
    isActive: true,
  },
  {
    thai: 'แกงจืด',
    roman: 'kaeng chut',
    en: 'clear soup',
    category: 'thai-food',
    type: 'dish',
    level: 'Intermediate',
    imageUrl: '/assets/food_drinks/kaeng_chut.jpg',
    emoji: '🍲',
    audioText: 'แกงจืด',
    tags: ['mild', 'soup'],
    isActive: true,
  },
  {
    thai: 'ไข่เจียว',
    roman: 'khai chiao',
    en: 'omelet',
    category: 'thai-food',
    type: 'dish',
    level: 'Intermediate',
    imageUrl: '/assets/food_drinks/khai_chiao.jpg',
    emoji: '🥚',
    audioText: 'ไข่เจียว',
    tags: ['simple', 'breakfast'],
    isActive: true,
  },
  {
    thai: 'น้ำเปล่า',
    roman: 'nam plao',
    en: 'plain water',
    category: 'thai-drink',
    type: 'drink',
    level: 'Intermediate',
    imageUrl: '/assets/food_drinks/nam_plao.jpg',
    emoji: '💧',
    audioText: 'น้ำเปล่า',
    tags: ['water', 'basic'],
    isActive: true,
  },
  {
    thai: 'น้ำแข็ง',
    roman: 'nam khaeng',
    en: 'ice',
    category: 'thai-drink',
    type: 'modifier',
    level: 'Intermediate',
    imageUrl: '/assets/food_drinks/nam_khaeng.jpg',
    emoji: '🧊',
    audioText: 'น้ำแข็ง',
    tags: ['modifier', 'cold'],
    isActive: true,
  },
  {
    thai: 'น้ำผลไม้',
    roman: 'nam phonlamai',
    en: 'juice',
    category: 'thai-drink',
    type: 'drink',
    level: 'Intermediate',
    imageUrl: '/assets/food_drinks/nam_phonlamai.jpg',
    emoji: '🧃',
    audioText: 'น้ำผลไม้',
    tags: ['juice', 'drink'],
    isActive: true,
  },
  {
    thai: 'ชาเย็น',
    roman: 'cha yen',
    en: 'thai iced tea',
    category: 'thai-drink',
    type: 'drink',
    level: 'Intermediate',
    imageUrl: '/assets/food_drinks/cha_yen.jpg',
    emoji: '🍵',
    audioText: 'ชาเย็น',
    tags: ['tea', 'popular'],
    isActive: true,
  },
  {
    thai: 'กาแฟเย็น',
    roman: 'kafe yen',
    en: 'iced coffee',
    category: 'thai-drink',
    type: 'drink',
    level: 'Intermediate',
    imageUrl: '/assets/food_drinks/kafe_yen.jpg',
    emoji: '☕',
    audioText: 'กาแฟเย็น',
    tags: ['coffee', 'popular'],
    isActive: true,
  },
  {
    thai: 'นมสด',
    roman: 'nom sod',
    en: 'fresh milk',
    category: 'thai-drink',
    type: 'drink',
    level: 'Intermediate',
    imageUrl: '/assets/food_drinks/nom_sod.jpg',
    emoji: '🥛',
    audioText: 'นมสด',
    tags: ['milk', 'drink'],
    isActive: true,
  },
  {
    thai: 'ไม่เผ็ด',
    roman: 'mai phet',
    en: 'not spicy',
    category: 'thai-modifier',
    type: 'modifier',
    level: 'Intermediate',
    imageUrl: '',
    emoji: '🌶️',
    audioText: 'ไม่เผ็ด',
    tags: ['spice-level', 'request'],
    isActive: true,
  },
  {
    thai: 'เผ็ดน้อย',
    roman: 'phet noi',
    en: 'less spicy',
    category: 'thai-modifier',
    type: 'modifier',
    level: 'Intermediate',
    imageUrl: '',
    emoji: '🌶️',
    audioText: 'เผ็ดน้อย',
    tags: ['spice-level', 'request'],
    isActive: true,
  },
  {
    thai: 'เผ็ดมาก',
    roman: 'phet mak',
    en: 'very spicy',
    category: 'thai-modifier',
    type: 'modifier',
    level: 'Intermediate',
    imageUrl: '',
    emoji: '🌶️',
    audioText: 'เผ็ดมาก',
    tags: ['spice-level', 'request'],
    isActive: true,
  },
  {
    thai: 'หวานน้อย',
    roman: 'wan noi',
    en: 'less sweet',
    category: 'thai-modifier',
    type: 'modifier',
    level: 'Intermediate',
    imageUrl: '',
    emoji: '🍯',
    audioText: 'หวานน้อย',
    tags: ['sweetness', 'request'],
    isActive: true,
  },
  {
    thai: 'หวานปกติ',
    roman: 'wan pokati',
    en: 'regular sweet',
    category: 'thai-modifier',
    type: 'modifier',
    level: 'Intermediate',
    imageUrl: '',
    emoji: '🍯',
    audioText: 'หวานปกติ',
    tags: ['sweetness', 'request'],
    isActive: true,
  },
  {
    thai: 'ไม่หวาน',
    roman: 'mai wan',
    en: 'no sugar',
    category: 'thai-modifier',
    type: 'modifier',
    level: 'Intermediate',
    imageUrl: '',
    emoji: '🍯',
    audioText: 'ไม่หวาน',
    tags: ['sweetness', 'request'],
    isActive: true,
  },
  {
    thai: 'ใส่ไข่',
    roman: 'sai khai',
    en: 'add egg',
    category: 'thai-modifier',
    type: 'modifier',
    level: 'Intermediate',
    imageUrl: '',
    emoji: '🥚',
    audioText: 'ใส่ไข่',
    tags: ['ingredient', 'request'],
    isActive: true,
  },
  {
    thai: 'ไม่ใส่ผงชูรส',
    roman: 'mai sai phong chu rot',
    en: 'no MSG',
    category: 'thai-modifier',
    type: 'modifier',
    level: 'Intermediate',
    imageUrl: '',
    emoji: '🧂',
    audioText: 'ไม่ใส่ผงชูรส',
    tags: ['ingredient', 'allergy'],
    isActive: true,
  },
  {
    thai: 'เมนูแนะนำคืออะไร',
    roman: 'menu nae nam kheu arai',
    en: 'What is recommended?',
    category: 'thai-phrase',
    type: 'question',
    level: 'Intermediate',
    imageUrl: '',
    emoji: '🍽️',
    audioText: 'เมนูแนะนำคืออะไร',
    tags: ['question', 'menu'],
    isActive: true,
  },
  {
    thai: 'ราคาเท่าไหร่',
    roman: 'rakha thao rai',
    en: 'How much?',
    category: 'thai-phrase',
    type: 'question',
    level: 'Intermediate',
    imageUrl: '',
    emoji: '💰',
    audioText: 'ราคาเท่าไหร่',
    tags: ['question', 'price'],
    isActive: true,
  },
  {
    thai: 'มีกับข้าวมังสวิรัติไหม',
    roman: 'mi kap khao mang sa wi rat mai',
    en: 'Do you have vegetarian options?',
    category: 'thai-phrase',
    type: 'question',
    level: 'Intermediate',
    imageUrl: '',
    emoji: '🥬',
    audioText: 'มีกับข้าวมังสวิรัติไหม',
    tags: ['question', 'diet'],
    isActive: true,
  },
  {
    thai: 'แพ้อาหารทะเล',
    roman: 'phae a han tha le',
    en: 'Allergic to seafood',
    category: 'thai-phrase',
    type: 'phrase',
    level: 'Intermediate',
    imageUrl: '',
    emoji: '🚫',
    audioText: 'แพ้อาหารทะเล',
    tags: ['allergy', 'health'],
    isActive: true,
  },
  {
    thai: 'ขออีกหนึ่งที่',
    roman: 'kho ik neung thi',
    en: 'One more, please',
    category: 'thai-phrase',
    type: 'phrase',
    level: 'Intermediate',
    imageUrl: '',
    emoji: '🙏',
    audioText: 'ขออีกหนึ่งที่',
    tags: ['request', 'polite'],
    isActive: true,
  },
  {
    thai: 'สั่งกลับบ้าน',
    roman: 'sang klap ban',
    en: 'Takeaway',
    category: 'thai-phrase',
    type: 'phrase',
    level: 'Intermediate',
    imageUrl: '',
    emoji: '🏠',
    audioText: 'สั่งกลับบ้าน',
    tags: ['order-type', 'service'],
    isActive: true,
  },
  {
    thai: 'ทานที่ร้าน',
    roman: 'than thi ran',
    en: 'For here',
    category: 'thai-phrase',
    type: 'phrase',
    level: 'Intermediate',
    imageUrl: '',
    emoji: '🪑',
    audioText: 'ทานที่ร้าน',
    tags: ['order-type', 'service'],
    isActive: true,
  },
  {
    thai: 'ขอช้อนส้อมเพิ่ม',
    roman: 'kho chon som pheum',
    en: 'Extra cutlery, please',
    category: 'thai-phrase',
    type: 'phrase',
    level: 'Intermediate',
    imageUrl: '',
    emoji: '🥄',
    audioText: 'ขอช้อนส้อมเพิ่ม',
    tags: ['request', 'service'],
    isActive: true,
  },
  {
    thai: 'คิดเงินด้วยครับ',
    roman: 'khit ngoen duai khrap',
    en: 'Check please',
    category: 'thai-phrase',
    type: 'phrase',
    level: 'Intermediate',
    imageUrl: '',
    emoji: '💳',
    audioText: 'คิดเงินด้วยครับ',
    tags: ['payment', 'polite'],
    isActive: true,
  },
  {
    thai: 'จ่ายด้วยบัตรได้ไหม',
    roman: 'chai duai bat dai mai',
    en: 'Can I pay by card?',
    category: 'thai-phrase',
    type: 'question',
    level: 'Intermediate',
    imageUrl: '',
    emoji: '💳',
    audioText: 'จ่ายด้วยบัตรได้ไหม',
    tags: ['payment', 'question'],
    isActive: true,
  },
  {
    thai: 'ขอใบเสร็จ',
    roman: 'kho bai set',
    en: 'Receipt, please',
    category: 'thai-phrase',
    type: 'phrase',
    level: 'Intermediate',
    imageUrl: '',
    emoji: '📄',
    audioText: 'ขอใบเสร็จ',
    tags: ['payment', 'request'],
    isActive: true,
  },
  {
    thai: 'ไม่เผ็ดได้ไหม',
    roman: 'mai phet dai mai',
    en: 'Can it be not spicy?',
    category: 'thai-phrase',
    type: 'question',
    level: 'Intermediate',
    imageUrl: '',
    emoji: '🌶️',
    audioText: 'ไม่เผ็ดได้ไหม',
    tags: ['request', 'spice'],
    isActive: true,
  },
];

// Seed Function
const DEFAULT_MONGO_URI = process.env.MONGODB_URI;

const seedIntermediateFoodDrinks = async (options = {}) => {
  const { mongoUri = DEFAULT_MONGO_URI, skipConnect = false } = options;

  if (!mongoUri) {
    throw new Error('MONGODB_URI is not defined');
  }

  try {
    if (!skipConnect) {
      await mongoose.connect(mongoUri, {
        useNewUrlParser: true,
        useUnifiedTopology: true,
      });
      console.log('✓ MongoDB connected for seeding Intermediate Food Drinks');
    }

    // Clear existing data
    await FoodDrinksVocab.deleteMany({});
    console.log('✓ Cleared existing data');

    // Insert new data
    const result = await FoodDrinksVocab.insertMany(foodDrinksData);
    console.log(`✓ Inserted ${result.length} food & drinks vocabulary items`);
  } catch (err) {
    console.error('✗ Seed error:', err);
    throw err;
  } finally {
    if (!skipConnect) {
      await mongoose.disconnect();
      console.log('✓ Connection closed');
    }
  }
};

if (require.main === module) {
  seedIntermediateFoodDrinks()
    .then(() => process.exit(0))
    .catch(async (err) => {
      console.error('✗ Seed error:', err);
      try {
        await mongoose.disconnect();
      } catch (disconnectError) {
        console.error('⚠️ Failed to disconnect MongoDB cleanly:', disconnectError);
      }
      process.exit(1);
    });
}

module.exports = seedIntermediateFoodDrinks;
