const mongoose = require('mongoose');
require('dotenv').config({ path: './config.env' });

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/thai-meow';

const idiomsSchema = new mongoose.Schema({
  thai: { type: String, required: true, index: true },
  literalTH: String,
  meaningTH: { type: String, required: true },
  meaningEN: String,
  exampleTH: String,
  exampleEN: String,
  audioText: String,
  register: { type: String, enum: ['neutral', 'formal', 'colloquial'], default: 'neutral' },
  tags: [String],
  level: { type: String, enum: ['Beginner', 'Intermediate', 'Advanced'], default: 'Advanced' },
  category: { type: String, default: 'thai-idioms' },
  imagePath: String,
  difficulty: { type: Number, min: 1, max: 5, default: 2 },
  isActive: { type: Boolean, default: true },
  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now },
});

const Idiom = mongoose.model('Idiom', idiomsSchema, 'thai_idioms');

const idiomsData = [
  {
    thai: 'น้ำขึ้นให้รีบตัก',
    literalTH: 'เมื่อน้ำขึ้นให้รีบตัก',
    meaningTH: 'ฉวยโอกาสเมื่อจังหวะดี',
    meaningEN: 'Seize the opportunity while it lasts',
    exampleTH: 'ช่วงนี้ลูกค้าสนใจเยอะ น้ำขึ้นให้รีบตัก!',
    exampleEN: 'The market is hot right now — strike while the iron is hot!',
    audioText: 'น้ำขึ้นให้รีบตัก',
    tags: ['โอกาส', 'เวลา'],
    level: 'Advanced',
    difficulty: 3,
  },
  {
    thai: 'ช้า ๆ ได้พร้าเล่มงาม',
    literalTH: 'ค่อย ๆ ทำจะได้ของดี',
    meaningTH: 'ค่อยเป็นค่อยไปจะได้ผลลัพธ์ที่ดี',
    meaningEN: 'Slow and steady wins the race',
    exampleTH: 'อย่ารีบเกินไป ช้า ๆ ได้พร้าเล่มงาม',
    exampleEN: 'Take your time — quality takes patience.',
    audioText: 'ช้า ๆ ได้พร้าเล่มงาม',
    tags: ['เวลา', 'คุณภาพ'],
    level: 'Advanced',
    difficulty: 2,
  },
  {
    thai: 'จับเสือมือเปล่า',
    literalTH: 'จับเสือโดยไม่มีอาวุธ',
    meaningTH: 'ทำเรื่องยากโดยไม่มีทุนหรือเครื่องมือ',
    meaningEN: 'Trying to gain something without investment',
    exampleTH: 'โครงการนี้อย่าจับเสือมือเปล่า ต้องมีแผนรองรับ',
    exampleEN: 'You cannot catch a tiger bare-handed.',
    audioText: 'จับเสือมือเปล่า',
    tags: ['ความเสี่ยง', 'งาน'],
    level: 'Advanced',
    difficulty: 3,
  },
  {
    thai: 'ตีสองหน้า',
    literalTH: 'ทำสองอย่างขัดแย้งกัน',
    meaningTH: 'แสดงท่าทีไม่จริงใจ',
    meaningEN: 'Two-faced or deceitful behavior',
    exampleTH: 'เขาทำดีต่อหน้าแต่พูดลับหลัง ตีสองหน้าแท้ ๆ',
    exampleEN: 'He acts nice but talks behind your back — two-faced.',
    audioText: 'ตีสองหน้า',
    tags: ['นิสัย', 'ความสัมพันธ์'],
    level: 'Advanced',
    difficulty: 2,
  },
  {
    thai: 'วัวหายล้อมคอก',
    literalTH: 'วัวหายแล้วค่อยล้อมคอก',
    meaningTH: 'แก้ปัญหาช้าเกินไปหลังจากเหตุเกิด',
    meaningEN: 'Fixing a problem only after it happens',
    exampleTH: 'ระบบโดนแฮ็กแล้วค่อยอัปเดต วัวหายล้อมคอก!',
    exampleEN: 'Updating after a hack — closing the barn door after the horse has bolted.',
    audioText: 'วัวหายล้อมคอก',
    tags: ['บทเรียน', 'ความเสี่ยง'],
    level: 'Advanced',
    difficulty: 2,
  },
  {
    thai: 'น้ำท่วมปาก',
    literalTH: 'น้ำล้นจนพูดไม่ได้',
    meaningTH: 'พูดไม่ได้เพราะเกรงใจหรือกลัว',
    meaningEN: 'Afraid or unable to speak up',
    exampleTH: 'เจ้านายอยู่ตรงนี้ น้ำท่วมปากพูดไม่ออก',
    exampleEN: 'With the boss here, I cannot say a thing.',
    audioText: 'น้ำท่วมปาก',
    tags: ['สังคม', 'ความสัมพันธ์'],
    level: 'Advanced',
    difficulty: 2,
  },
  {
    thai: 'กินบนเรือนขี้รดบนหลังคา',
    literalTH: 'อยู่ในบ้านแล้วยังทำให้เสีย',
    meaningTH: 'เนรคุณผู้มีพระคุณ',
    meaningEN: 'Bite the hand that feeds you',
    exampleTH: 'อย่ากินบนเรือนขี้รดบนหลังคา!',
    exampleEN: 'Do not betray those who supported you.',
    audioText: 'กินบนเรือนขี้รดบนหลังคา',
    tags: ['คุณธรรม', 'เตือนสติ'],
    level: 'Advanced',
    difficulty: 4,
  },
  {
    thai: 'เก็บเบี้ยใต้ถุนร้าน',
    literalTH: 'เก็บเงินเหรียญใต้ร้านค้า',
    meaningTH: 'เก็บเล็กผสมน้อยทีละนิด',
    meaningEN: 'Save small amounts over time',
    exampleTH: 'ทำงานเสริมเก็บเบี้ยใต้ถุนร้านไว้ก่อน',
    exampleEN: 'Every small saving counts.',
    audioText: 'เก็บเบี้ยใต้ถุนร้าน',
    tags: ['เงิน', 'ประหยัด'],
    level: 'Advanced',
    difficulty: 2,
    register: 'colloquial',
  },
  {
    thai: 'บัวไม่ให้ช้ำน้ำไม่ให้ขุ่น',
    literalTH: 'รักษาบัวและน้ำให้ดี',
    meaningTH: 'ทำให้ทุกฝ่ายพอใจ ไม่ให้ขัดแย้ง',
    meaningEN: 'Keep peace and harmony between all sides',
    exampleTH: 'ประชุมวันนี้ต้องบัวไม่ให้ช้ำน้ำไม่ให้ขุ่น',
    exampleEN: 'We need to keep everyone happy in the meeting.',
    audioText: 'บัวไม่ให้ช้ำน้ำไม่ให้ขุ่น',
    tags: ['ประนีประนอม', 'วัฒนธรรม'],
    level: 'Advanced',
    difficulty: 3,
  },
  {
    thai: 'ปิดทองหลังพระ',
    literalTH: 'ปิดทองด้านหลังพระ',
    meaningTH: 'ทำความดีโดยไม่หวังชื่อเสียง',
    meaningEN: 'Do good without seeking recognition',
    exampleTH: 'เขาช่วยอยู่เบื้องหลัง ปิดทองหลังพระจริง ๆ',
    exampleEN: 'He works behind the scenes, doing good quietly.',
    audioText: 'ปิดทองหลังพระ',
    tags: ['คุณธรรม', 'เสียสละ'],
    level: 'Advanced',
    difficulty: 3,
    register: 'formal',
  },
  {
    thai: 'ยืมจมูกคนอื่นหายใจ',
    literalTH: 'ใช้จมูกคนอื่นเพื่อหายใจ',
    meaningTH: 'พึ่งพาคนอื่นมากเกินไปจนทำอะไรเองไม่ได้',
    meaningEN: 'Rely too much on others',
    exampleTH: 'อย่าพึ่งคนอื่นมากเกินไป ยืมจมูกคนอื่นหายใจไม่ได้ตลอดไป',
    exampleEN: 'You cannot depend on others forever.',
    audioText: 'ยืมจมูกคนอื่นหายใจ',
    tags: ['พึ่งพา', 'นิสัย'],
    level: 'Advanced',
    difficulty: 2,
    register: 'colloquial',
  },
  {
    thai: 'สีซอให้ควายฟัง',
    literalTH: 'สีซอแต่คนไม่ฟัง',
    meaningTH: 'อธิบายให้คนที่ไม่เข้าใจหรือไม่สนใจฟัง',
    meaningEN: 'Trying to teach someone who refuses to learn',
    exampleTH: 'พูดไปก็สีซอให้ควายฟัง',
    exampleEN: 'It is like casting pearls before swine.',
    audioText: 'สีซอให้ควายฟัง',
    tags: ['สื่อสาร', 'ท้อแท้'],
    level: 'Advanced',
    difficulty: 3,
  },
  {
    thai: 'ลูบหน้าปะจมูก',
    literalTH: 'ลูบหน้าแต่ไปโดนจมูก',
    meaningTH: 'ช่วยพวกพ้องจนกระทบผู้อื่น',
    meaningEN: 'Show favoritism that affects others',
    exampleTH: 'อย่าลูบหน้าปะจมูก ต้องยุติธรรมกับทุกฝ่าย',
    exampleEN: 'Do not show favoritism — be fair to everyone.',
    audioText: 'ลูบหน้าปะจมูก',
    tags: ['สังคม', 'วัฒนธรรม'],
    level: 'Advanced',
    difficulty: 2,
    register: 'colloquial',
  },
  {
    thai: 'ขี่ช้างจับตั๊กแตน',
    literalTH: 'ใช้ช้างไปจับตั๊กแตน',
    meaningTH: 'ใช้วิธีเกินความจำเป็นกับเรื่องเล็ก',
    meaningEN: 'Overdoing something small',
    exampleTH: 'เรื่องเล็กนิดเดียวอย่าขี่ช้างจับตั๊กแตน',
    exampleEN: 'Do not use a cannon to kill a mosquito.',
    audioText: 'ขี่ช้างจับตั๊กแตน',
    tags: ['เวลา', 'การตัดสินใจ'],
    level: 'Advanced',
    difficulty: 2,
  },
  {
    thai: 'เข้าตากรรมการ',
    literalTH: 'เข้าตาผู้ตัดสิน',
    meaningTH: 'ทำได้ดีจนผู้ใหญ่หรือกรรมการชอบใจ',
    meaningEN: 'To impress someone important',
    exampleTH: 'งานของเธอเข้าตากรรมการจริง ๆ',
    exampleEN: 'Her work really impressed the judges.',
    audioText: 'เข้าตากรรมการ',
    tags: ['ยกย่อง', 'งาน'],
    level: 'Advanced',
    difficulty: 2,
  },
  {
    thai: 'น้ำผึ้งหยดเดียว',
    literalTH: 'น้ำผึ้งเพียงหยดเดียวทำให้ขุ่น',
    meaningTH: 'เรื่องเล็กอาจกลายเป็นเรื่องใหญ่ถ้าไม่ระวัง',
    meaningEN: 'A small issue can lead to a big problem',
    exampleTH: 'อย่าประชดกันเลย เดี๋ยวกลายเป็นน้ำผึ้งหยดเดียว',
    exampleEN: 'Do not be sarcastic — it could escalate quickly.',
    audioText: 'น้ำผึ้งหยดเดียว',
    tags: ['ความสัมพันธ์', 'บทเรียน'],
    level: 'Advanced',
    difficulty: 3,
  },
  {
    thai: 'งมเข็มในมหาสมุทร',
    literalTH: 'งมหาเข็มในทะเล',
    meaningTH: 'ทำเรื่องยากมากหรือแทบเป็นไปไม่ได้',
    meaningEN: 'Nearly impossible to find',
    exampleTH: 'หาหลักฐานตอนนี้เหมือนงมเข็มในมหาสมุทร',
    exampleEN: 'Finding proof now is like finding a needle in a haystack.',
    audioText: 'งมเข็มในมหาสมุทร',
    tags: ['ความยาก', 'บทเรียน'],
    level: 'Advanced',
    difficulty: 3,
    register: 'formal',
  },
  {
    thai: 'เสียน้อยเสียยาก เสียมากเสียง่าย',
    literalTH: 'ไม่ยอมเสียเล็กน้อยจนต้องเสียมาก',
    meaningTH: 'ยอมเสียเล็กน้อยตอนนี้ดีกว่าเสียมากทีหลัง',
    meaningEN: 'Better lose small now than big later',
    exampleTH: 'เปลี่ยนอะไหล่เถอะ เสียน้อยเสียยาก เสียมากเสียง่าย',
    exampleEN: 'Fix it early — do not wait till it breaks completely.',
    audioText: 'เสียน้อยเสียยาก เสียมากเสียง่าย',
    tags: ['การตัดสินใจ', 'เงิน'],
    level: 'Advanced',
    difficulty: 2,
  },
  {
    thai: 'กินแห้ว',
    literalTH: 'กินหัวแห้ว (พืชหัว)',
    meaningTH: 'ผิดหวังหรือพลาดโอกาส',
    meaningEN: 'To be disappointed or rejected',
    exampleTH: 'สมัครงานแล้วกินแห้วอีกแล้ว',
    exampleEN: 'I applied for that job and got rejected again.',
    audioText: 'กินแห้ว',
    tags: ['ผิดหวัง', 'ร่วมสมัย'],
    level: 'Advanced',
    difficulty: 1,
    register: 'colloquial',
  },
  {
    thai: 'ส้มหล่น',
    literalTH: 'ส้มตกใส่',
    meaningTH: 'ได้สิ่งดีโดยไม่คาดคิด',
    meaningEN: 'A lucky chance or unexpected fortune',
    exampleTH: 'ได้ตั๋วฟรี ส้มหล่นเลย!',
    exampleEN: 'Got free tickets — what a windfall!',
    audioText: 'ส้มหล่น',
    tags: ['โชคดี', 'ร่วมสมัย'],
    level: 'Advanced',
    difficulty: 1,
    register: 'colloquial',
  },
];

const seedIdioms = async () => {
  try {
    await mongoose.connect(MONGODB_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });

    console.log('✅ Connected to MongoDB');

    // Clear existing idioms
    await Idiom.deleteMany({ category: 'thai-idioms' });
    console.log('🗑️  Cleared existing idioms');

    // Insert new idioms
    const inserted = await Idiom.insertMany(idiomsData);
    console.log(`✅ Successfully seeded ${inserted.length} idioms`);

    await mongoose.connection.close();
    console.log('✅ Database connection closed');
  } catch (error) {
    console.error('❌ Error seeding idioms:', error);
    process.exit(1);
  }
};

// Run seed
seedIdioms();
